### ISSUE TITLE
Gone in 60 seconds when "admin/security/session_cookie_lifetime" not set

### ISSUE THREAD

**Issue by jeroenvermeulen** [colinmollenhour/Cm_RedisSession#104]
Hi @colinmollenhour,

Today we had the second case of a shop having the problem of being kicked out of the backend after only 60 seconds of inactivity. You can image this is a frustrating situation for shop owners.
So I investigated a bit deeper this time.

I discovered in these shops the config field `admin/security/session_cookie_lifetime` was empty.
In [Model/Session/Config.php line 130](https://github.com/colinmollenhour/Cm_RedisSession/blob/master/code/Model/Session/Config.php#L129-L130) this config field is retrieved. When the field is empty, the result will be NULL and later on the value of `min_lifetime` from `local.xml` will be used.

**Would it help if I propose a pull request with a fix for this, or maybe you can create a quick fix for it yourself?**

For these customers the solution was simply to set the config field, which I used N98 for:
```
n98-magerun.phar config:get admin/security/session_cookie_lifetime | grep -P "Couldn't find|NULL" &&  n98-magerun.phar config:set admin/security/session_cookie_lifetime 3600 && n98-magerun.phar cache:clean config
```
For the future it would be nice to have this fixed, so other people don't need to investigate the same problem. I don't know how the config field became empty. Can't image both of these customers did it on purpose.

**Comment by colinmollenhour** [comment]
It is definitely not good for this field to not have a default value, but it seems this should be a Magento fix since it originates there.. 

Perhaps just a README notice would be more appropriate since the best fix really is for the user to set whatever value is appropriate for their store (although I think Magento should choose a sane default like at least 3 hours (considering PCI requirements are pretty strict).

**Comment by sprankhub** [comment]
Just ran into the same issue. Since Magento has no default value for `admin/security/session_cookie_lifetime`, I think this should really be fixed in this extension.

**Comment by colinmollenhour** [comment]
Why not use OpenMage/magento-lts where this has already been fixed? The backend should not be responsible for determining app-level config like cookie lifetimes.

**Comment by sprankhub** [comment]
The issue is that by default, if `admin/security/session_cookie_lifetime` is empty (which is the default!), Magento falls back to the normal cookie lifetime, which is 3600 by default. Hence, what happened for me was:

* Used file session storage. Admin sessions were active for 3600 seconds.
* Switched to `Cm_RedisSession`. Noticed that the admin session was only active for 60 seconds.
* Searched for the solution. Found out that when using this module, the config value `admin/security/session_cookie_lifetime` needs to be set.

This is not the way I would expect. Usually, switching the session backend should not change the session lifetime IMHO.

**Comment by colinmollenhour** [comment]
Fixed in 26b47113462caa98f724d3242a761d2f2e7c4186 by using the cookie lifetime if the admin lifetime is empty.

**Comment by jeroenvermeulen** [comment]
Good work. Thanks for the fix @colinmollenhour

**Comment by sprankhub** [comment]
Thanks @colinmollenhour!
