### ISSUE TITLE
Magento 1 compatibility?

### ISSUE THREAD

**Issue by craigcarnell** [colinmollenhour/Cm_RedisSession#126]
What is the latest release compatible with Magento 1?

**Comment by colinmollenhour** [comment]
All releases on this repo are for M1. That said, you cannot always mix-n-match Cm_RedisSession, php-redis-session-abstract and Credis so if you update Cm_RedisSession update cm-redis-session-abstract, Credis and Cm_Cache_Backend_Redis as well. The last release was a little bumpy but I believe all issues are fixed in the latest tagged versions for both composer and modman installs.
