### ISSUE TITLE
Cm_RedisSession_Local.xml

### ISSUE THREAD

**Issue by seansan** [colinmollenhour/Cm_RedisSession#136]
Hi, I see in modman Cm_RedisSession is renamed to Cm_RedisSession_Local.xml

Cm_RedisSession.xml                             app/etc/modules/Cm_RedisSession_Local.xml

I did not see this before (we used FTP some time ago) now modman --copy .... hey! and there is the extra XML. 

1. I imagine we need to disable Cm_RedisSession.xml? if we use Cm_RedisSession_Local.xml
2. is it smart to add something about this to the README?

thanks, Sean

**Comment by colinmollenhour** [comment]
The merge process will behave as "last value wins" and the files in `app/etc/modules` are sorted lexicographically so if both files exist the first one will become ineffective. If using modman --copy then you could delete either but it is not necessary as long as you know which one to edit. The modman file was changed almost two years ago because when Magento started packaging it with core code it created a conflict for people using the latest version from github. Is this file creating a problem somehow?

**Comment by seansan** [comment]
hi! the problem for me was that
- I would not expect a rename in modman .... rather then in the original
filename, I consider modman only for putting files in the right place
- that being said: original CM xml contains codepool community, and this
one local: so in this case I would suggest overwriting the original XML file
- another option woul be to include the original Cm_redissession.xml file
with FALSE in it: now when you install this version of redis_session
(knowingly) you will activate  Cm_redissession_local.xml containing true
and overwrite Cm_redissession.xml with a value of false

Hope this is clear

**Comment by colinmollenhour** [comment]
I can see your point about the file being renamed in modman. However, the reason for not overwriting Cm_RedisSession.xml is that if you are getting Magento core code from a VCS then your working tree will always be dirty. So, how about just renaming the actual file in the repo (to Cm_RedisSession_Local.xml) so that the symlink name matches the real file name and leaving it at that?

**Comment by seansan** [comment]
Hmm yes can do

But still risk of having 2 codepools

Not sure of the real risk

But sounds illogical
