### ISSUE TITLE
$config->descend('...') return object

### ISSUE THREAD

**Issue by lemaryn** [colinmollenhour/Cm_RedisSession#52]
$config->descend('host') return object, and it never to be empty, please change 
(string)       ($config->descend('host') ?: '127.0.0.1'); 
to
((string)$config->descend('host') ?: '127.0.0.1'); 

change
(int)          ($config->descend('port') ?: '6379');
to
((int)$config->descend('port') ?: '6379');

and etc....

**Comment by huguesalary** [comment]
I second that bug.

All the calls:
`(string) ($config->descend('host') ?: '127.0.0.1');` yield an unwanted result.

`$config->descend('host')` will always return `true`, even if the `<host></host>` node is empty.

This causes a serious problem here:

```
$this->_useLocking = defined('CM_REDISSESSION_LOCKING_ENABLED')
                    ? CM_REDISSESSION_LOCKING_ENABLED
                    : ! ($config->disable_locking ?: self::DEFAULT_DISABLE_LOCKING);
```

`! ($config->disable_locking ?: self::DEFAULT_DISABLE_LOCKING)` always returns false. Which means that `_useLocking` is always `false`, which means that locking is never used.

Here's an example for different values of the `<disable_locking>` node:
`<disable_locking>0</disable_locking>` --->  `! ($config->disable_locking ?: self::DEFAULT_DISABLE_LOCKING) // false` 
`<disable_locking>1</disable_locking>` --->  `! ($config->disable_locking ?: self::DEFAULT_DISABLE_LOCKING) // false` 
`<disable_locking>true</disable_locking>` --->  `! ($config->disable_locking ?: self::DEFAULT_DISABLE_LOCKING) // false` 
`<disable_locking>false</disable_locking>` --->  `! ($config->disable_locking ?: self::DEFAULT_DISABLE_LOCKING) // false`

**Comment by colinmollenhour** [comment]
(string) ($config->descend('host') ?: '127.0.0.1');

The first expression to be evaluated here is $config->descend('host'). If no node exists this is falsey so the string '127.0.0.1' is returned. If a node does exist the ternary expression evaluates to the node which is then cast to a string. If a user specifies an empty node then an empty string must be what the user wants, right? I suppose it is subjective, but if you want to use the defaults then you should just not specify those nodes at all. If you do specify nodes then it will take them literally, for better or for worse.

However, the $config->descend('disable_locking') is cast directly to a bool instead of to a string first and then a bool so you are right that this is a bug. Locking is enabled if no "disable_locking" node is specified, though.

Thanks, both for the issue report.

**Comment by huguesalary** [comment]
> If a user specifies an empty node then an empty string must be what the user wants, right? I suppose it is subjective

I hadn't seen it that way, it's definitely subjective. After thinking more about it, I can see that a user may want to supplie an empty string value (even if, in the case of the <host> node for example, it makes absolutely no sense). So, although not necessarily the most intuitive, your approach is the most flexible one.

Thanks for the bugfix!
