### ISSUE TITLE
Random 503's in production environment

### ISSUE THREAD

**Issue by senthilengg05** [colinmollenhour/Cm_RedisSession#69]
First of all thank you for such a great module.

We are running with a 6 frontend cluster and one for backend (admin), when we review the logs in splunk we are seeing 2-3 ips getting 503's in a day span. We are skeptical because the holiday season is going to kick start this Thursday.  When I review the closed issue #35 it says 503's could be possible if we generate large image gallery on demand.

Though we are not generating large galleries, we are seeing 503's randomly in production. I've reviewed the nginx logs as well there are not more than 2 hits to a particular page with the second. Can you please analyse and provide your thoughts ?

Error Message in the log :: Session concurrency exceeded for ID sess_i0fa3rjbcb8ucfvi9cn4vovt87; displaying HTTP 503 (6 waiting, 21 total requests)
  /en_store_view/checkout/cart/? (******- Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36)"

Note :: Its only happening in the production environment not even in staging though we run our selenium scripts in parallel.

**Comment by colinmollenhour** [comment]
This space is really for bug reporting and new features, not consulting..

The sessions are locked individually so the admin user who views a large gallery is not affecting other users so is not a concern to scaling. This should be fixed by fixing the gallery thumbnails to be cached.

Regarding generation of things like cache and JS/CSS files this also is not really related to sessions. That shoudl be fixed by implementing proper file locking (Magento core does not).

If you are concerned about scaling, identify where locking is a problem (e.g. multiple Magento-generated images appear on one page that can't be cached).
