### ISSUE TITLE
Giving up on obtaining lock

### ISSUE THREAD

**Issue by mpchadwick** [colinmollenhour/Cm_RedisSession#85]
In [this section of the code](https://github.com/colinmollenhour/Cm_RedisSession/blob/bdd9824e44b84956034dd3a78d17336c31137833/code/Model/Session.php#L315-L322) it gives up on obtaining a lock if `$tries >= $breakAfter + $this->_failAfter`. We can configure `$breakAfter` [here](https://github.com/colinmollenhour/Cm_RedisSession/blob/bdd9824e44b84956034dd3a78d17336c31137833/code/Model/Session.php#L705) but `$this->_failAfter` is [not something we have control over](https://github.com/colinmollenhour/Cm_RedisSession/blob/bdd9824e44b84956034dd3a78d17336c31137833/code/Model/Session.php#L134). In other words, even if we set `$breakAfter` to 0, we'd still have to wait for the amount of time set in the constants as `$this->_failAfter` (30 seconds?) before we bail. 

```
# php -r "echo round((1000000 / 500000) * 15);"                                                                               
30
```

Am I reading this correctly? If so it seems like `$breakAfter` is a bit misleading, and also seems like missing functionality that we can't truly configure the timeout. Maybe I'm just reading the code wrong or maybe line 316 is really supposed to be?

```php
if ($tries >= $breakAfter) {
```

**Comment by colinmollenhour** [comment]
It has been so long since I wrote this but I believe the general idea was:

* First try to get a write lock (will block other requests for same session)
* Then try to steal the lock from the request that has it currently.
* Then just give up and continue with no locking.

The reason for the intermediate step is that if you have say 5 requests, one has the lock and 4 are waiting for the lock but the one that has the lock is abnormally slow rather than abandoning locking altogether if another process gets the lock then hope that it won't also be super slow. Of course this is subjective and the usefulness depends on the individual situation so I think the best thing would be to just make that configurable as well rather than remove it altogether.

**Comment by mpchadwick** [comment]
👍 I'll update my PR.
