### ISSUE TITLE
Session concurrency exceeded for ID

### ISSUE THREAD

**Issue by bhargawrss** [colinmollenhour/Cm_RedisSession#94]
I am getting this error redis_session.log file :
**Session concurrency exceeded for ID sess_ecc85b7f599532a2964eb919a2e34e9f;** displaying HTTP 503 (6 waiting, 19 total requests)  /search/?q=Alphabets+Stickers (223.227.15.91 - Mozilla/5.0 (Linux; Android 6.0.1; ONE A2003 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.98 Mobile Safari/537.36)

1. What exactly the above error means and it is coming ?

2. What will be the effect on the server if I increase DEFAULT_MAX_CONCURRENCY in the redis settings php file and will this help the above problem ?

3. The RAM is almost 95% consumed on the server and there is cache of 7GB, even after setting the max memory  and maxmemory_policy  to allkeys_lru in the redis conf file.(8 GB Ram Server VPS)

4. Disabling Redis : Will it cause any problem on the server and will it is solve this issue.

5.  I have also set the maxmemory in Redis log file to 2GB, still the cache is going to 6gb.. How to track or identify it ?

I need a help and some ray of information on the above issue asap please.

**Comment by colinmollenhour** [comment]
The message can generally be ignored. It shows "6 waiting" which means somehow the user has 7 simultaneous requests hitting Magento so either the user is a bot using a high request concurrency or there is something wrong with your page such as lots of images that are 404 and hitting Magento when they should just be static files.

Regarding disabling Redis, if you are on a single-server environment and aren't using replication then using the file backend is generally a good choice as there is really nothing wrong with it, it just isn't good for multi-node environments due to file systems naturally not being distributed.
