### ISSUE TITLE
1500ms+ read times for sessions

### ISSUE THREAD

**Issue by urifoox** [colinmollenhour/Cm_RedisSession#97]
Hi,

Looking at NewRelic traces we keep seeing instances where Cm_RedisSession_Model_Session::read is taking an extraordinary amount of time. We've turned on the error logging to the highest setting and see we cannot find an instance where we see anywhere near these times being logged. Has anyone experience this before and have any ideas on what it could be? Any help is appreciated!

Here is our XML config

 ```
       <redis_session>
            <host>xxx</host>
            <port>xxx</port>
            <password>xxx</password>
            <timeout>2.5</timeout>
            <persistent></persistent>
            <db>xxx</db>
            <compression_threshold>0</compression_threshold>
            <compression_lib>gzip</compression_lib>
            <log_level>0</log_level>
            <max_concurrency>20</max_concurrency>
            <break_after_frontend>3</break_after_frontend>
            <break_after_adminhtml>30</break_after_adminhtml>
            <first_lifetime>600</first_lifetime>
            <bot_first_lifetime>60</bot_first_lifetime>
            <bot_lifetime>7200</bot_lifetime>
            <disable_locking>0</disable_locking>
            <min_lifetime>60</min_lifetime>
            <max_lifetime>1209600</max_lifetime>
        </redis_session>

```

This is what we see in New Relic
Component/Count/Duration
Cm_RedisSession_Model_Session::read	1	1,520 ms	
Cm_RedisSession_Model_Session::read	1	2,396 ms	
Cm_RedisSession_Model_Session::read	1	4,521 ms

**Comment by colinmollenhour** [comment]
In my experience this is always due to a high-concurrency session and never a single page load because there is no lock contention with normal single-page loads. You can confirm by checking getFailedLockAttempts. I would also check all activity for the sessions which exhibited the issue and see what their access pattern is like to look for anomalies or abuse patterns. Also confirm there are no bugs on the site causing a bunch of 404s (e.g. if image urls were wrong due to a browser-specific bug). Depending on what is causing it you can either fix the problem, tune your error reporting somehow, ignore it, etc.
