### ISSUE TITLE
Error in assuming redis_session is defined in configuration

### ISSUE THREAD

**Issue by kirkmadera** [colinmollenhour/Cm_RedisSession#99]
We run some environments with redissession enabled and some without. The module now assumes that the global/redis_session key is populated in Magento configuration. When it is not, the following error is displayed:

```
[03-Jan-2017 21:02:20 UTC] PHP Fatal error:  Call to a member function descend() on boolean in /var/www/myproject/vendor/colinmollenhour/magento-redis-session/code/Model/Session/Config.php on line 49
```

The module should instead, do nothing (or maybe write a notice to a log) when no redis_session node is defined in configuration.

I suppose disabling the module for specific environments is another option, but might not fit into everyone's Magento 1 workflow.

**Comment by colinmollenhour** [comment]
Thanks for the report, I'll change it to use an empty element instead so essentially suppressing the error.. However, note that unless the session handler is configured to be 'db', then none of this Cm_RedisSession code should ever be loaded. Unfortunately since Magento did not create opportunity for registering custom handlers without rewriting other core files the module *must* assume that if it is present then it is intended to replace the 'db' handler. So, if you want to use MySQL session handler then you need to make sure this module is not active.

**Comment by kirkmadera** [comment]
Thanks, this will solve the problem for our setup.

**Comment by kirkmadera** [comment]
This still didn't resolve the issue. The session rewrite rule still happens for some reason even after disabling the module which doesn't make any sense to me... I tried manually clearing cache also. I also tried setting it to file. No matter what, it still loads the module's rewrite rule. This is ugly, but I ended up just reversing the rewrite rule in my local.xml on the one environment that is not running Redis. I'm not sure how this was not an issue with older code or what is different now. I think the difference is the rewrite rule actually. Since this used to be part of "core" code and now we're trying to move it out and use a more up to date version.

Well.. ugly, but this does seem to work:

```
# app/etc/local.xml
<?xml version="1.0"?>
<config>
    <global>
        ...
        <session_save><![CDATA[db]]></session_save>
        <models>
            <core_mysql4>
                <rewrite>
                    <session>Mage_Core_Model_Resource_Session</session>
                </rewrite>
            </core_mysql4>
        </models>
    </global>
</config>
```

**Comment by colinmollenhour** [comment]
I have no idea how the rewrite could be active if the module is either missing or inactive in the app/etc/modules directory and cache was properly cleaned...

**Comment by kirkmadera** [comment]
I figured out why. You have a Cm_RedisSession_Local.xml that includes Cm_RedisSession and Cm_RedisSession_Local. Is there any reason for this file to include both? Why not just leave the Cm_RedisSession.xml alone?

That was the source of my confusion. It's also causing me some grief right now in my build process because I can't just simply disable it with `n98-magerun dev:module:disable Cm_RedisSession`.

**Comment by kirkmadera** [comment]
If anyone else runs into this, you can disable the module by running this 

```
sed -i 's|true|false|g' htdocs/app/etc/modules/Cm_RedisSession_Local.xml
```

**Comment by colinmollenhour** [comment]
Cm_RedisSession_Local.xml is not part of this repo. Perhaps it was created by n98-magerun?

**Comment by colinmollenhour** [comment]
Oops, correction.. The modman file links Cm_RedisSession.xml as Cm_RedisSession_Local.xml.. I did this when Magento started bundling it with the core so that people could easily use the github version over the core version without having to overwrite files. I suppose n98-magerun is not expecting this extra file.
